// ===================================================================
// This file was created by the CRM Tooling for Rational Rose
//   Version 1.6
// It contains the required IBM-defined qualifiers
// ===================================================================


Qualifier IBM_HasInstances : boolean = false, Scope(class, association),
    Flavor(restricted);


Qualifier IBM_HasProvider : boolean = false, Scope(class, association),
    Flavor(restricted);


Qualifier IBM_ImplementationType : string = "NotSupported", Scope(property, method),
    Flavor(restricted);


