// ===================================================================
// This file was created using ECUTE.
//   Version 2.1 beta 1h
//   by exporting package Linux_Samba
//   from model Linux_Samba-Model
//   on 9/12/2005
// Origin of package: Manually created
// ===================================================================


// ===================================================================
// Linux_SambaServiceConfiguration
// ===================================================================
[Description ("Class representing Samba configuration. Its the anchor for the "
    "Linux_SambaSettings class")]
class Linux_SambaServiceConfiguration : CIM_Configuration {

    [Write, Description ("Fully qualified configuration file e.g. /etc/smb.conf")]
    string ConfigurationFile;

    [Key, Override ("Name"), Description (
        "Id of the Samba Service for this configuration")]
    string Name;
};


// ===================================================================
// Linux_SambaShareFileNameHandlingOptions
// ===================================================================
[Description ("Class representing the file name handling options for a share.")]
class Linux_SambaShareFileNameHandlingOptions : CIM_SettingData {

    [Write, Description ("controls whether filenames are case sensitive")]
    boolean CaseSensitive;

    [Write]
    boolean DosFiletimes;

    [Write, Description ("Whether files starting with a dot appear as hidden files")]
    boolean HideDotFiles;

    [Key]
    string Name;
};


// ===================================================================
// Linux_SambaShareOptions
// ===================================================================
[Description ("This class represents the collection of share  specific definitions")]
class Linux_SambaShareOptions : CIM_SettingData {

    [Write, Description ("Is the share enabled or disabled")]
    boolean Available;

    [Write, Description ("Self descriptory")]
    string Comment;

    [Key, Description ("Name of Share")]
    string Name;

    [Write, Description ("Specifies the share related  path")]
    string Path;

    [Write]
    boolean Printable;
};


// ===================================================================
// Linux_SambaShareSecurityOptions
// ===================================================================
[Description("")]
class Linux_SambaShareSecurityOptions : CIM_SettingData {

    [Write]
    uint16 CreateMask;

    [Write]
    uint16 DirectoryMask;

    [Write]
    uint16 DirectorySecurityMask;

    [Key, Description ("Name of Share to which these options belong to ")]
    string Name;
};


// ===================================================================
// Linux_SambaService
// ===================================================================
[Description ("Service Process Identifier")]
class Linux_SambaService : CIM_Service {

    [Key, Override ("Name")]
    string Name;

    [Write]
    boolean Started;
};


// ===================================================================
// Linux_SambaGlobalOptions
// ===================================================================
[Description("")]
class Linux_SambaGlobalOptions : CIM_SettingData {

    [Write, Description (
        "This global parameter allows the Samba admin to limit what "
        "interfaces on a machine will serve SMB requests. It affects "
        "file service smbd(8) and name service nmbd(8) in a slightly "
        "different ways.\n"
        "For name service it causes nmbd to bind to ports 137 and 138"
        " on the interfaces listed in the interfaces parameter. nmbd "
        "also binds to the \"all addresses\" interface (0.0.0.0) on "
        "ports 137 and 138 for the purposes of reading broadcast "
        "messages. If this option is not set then nmbd will service "
        "name requests on all of these sockets. If bind interfaces "
        "only is set then nmbd will check the source address of any "
        "packets coming in on the broadcast sockets and discard any "
        "that don't match the broadcast addresses of the interfaces "
        "in the interfaces parameter list. As unicast packets are "
        "received on the other sockets it allows nmbd to refuse to "
        "serve names to machines that send packets that arrive "
        "through any interfaces not listed in the interfaces list. IP"
        " Source address spoofing does defeat this simple check,"
        " however, so it must not be used seriously as a security "
        "feature for nmbd.\n"
        "For file service it causes smbd(8) to bind only to the "
        "interface list given in the interfaces parameter. This "
        "restricts the networks that smbd will serve to packets "
        "coming in those interfaces. Note that you should not use "
        "this parameter for machines that are serving PPP or other "
        "intermittent or non-broadcast network interfaces as it will "
        "not cope with non-permanent interfaces.\n"
        "If bind interfaces only is set then unless the network "
        "address 127.0.0.1 is added to the interfaces parameter list "
        "smbpasswd(8) and swat(8) may not work as expected due to the"
        " reasons covered below.\n"
        "To change a users SMB password, the smbpasswd by default "
        "connects to the localhost - 127.0.0.1 address as an SMB "
        "client to issue the password change request. If bind "
        "interfaces only is set then unless the network address "
        "127.0.0.1 is added to the interfaces parameter list then "
        "smbpasswd will fail to connect in it's default mode. "
        "smbpasswd can be forced to use the primary IP interface of "
        "the local host by using its smbpasswd(8) -r remote machine "
        "parameter, with remote machine set to the IP name of the "
        "primary interface of the local host.\n"
        "The swat status page tries to connect with smbd and nmbd at "
        "the address 127.0.0.1 to determine if they are running. Not "
        "adding 127.0.0.1 will cause smbd and nmbd to always show "
        "\"not running\" even if they really are. This can prevent "
        "swat from starting/stopping/restarting smbd and nmbd.")]
    boolean BindInterfacesOnly;

    [Write, Description (
        "This option allows you to override the default network "
        "interfaces list that Samba will use for browsing, name "
        "registration and other NBT traffic. By default Samba will "
        "query the kernel for the list of all active interfaces and "
        "use any interfaces except 127.0.0.1 that are broadcast "
        "capable.\n"
        "The option takes a list of interface strings. Each string "
        "can be in any of the following forms:\n"
        " - a network interface name (such as eth0). This may include"
        " shell-like wildcards so eth* will match any interface "
        "starting with the substring \"eth\".\n"
        " - an IP address. In this case the netmask is determined "
        "from the list of interfaces obtained from the kernel.\n"
        " - an IP/mask pair.\n"
        " - a broadcast/mask pair.\n"
        "\nThe \"mask\" parameters can either be a bit length (such "
        "as 24 for a C class network) or a full netmask in dotted "
        "decimal form.\n"
        "The \"IP\" parameters above can either be a full dotted "
        "decimal IP address or a hostname which will be looked up via"
        " the OS's normal hostname resolution mechanisms.")]
    string Interfaces;

    [Key]
    string Name;

    [Write, Description (
        "This is a list of NetBIOS names that nmbd will advertise as "
        "additional names by which the Samba server is known. This "
        "allows one machine to appear in browse lists under multiple "
        "names. If a machine is acting as a browse server or logon "
        "server none of these names will be advertised as either "
        "browse server or logon servers, only the primary name of the"
        " machine will be advertised with these capabilities.")]
    string NetbiosAlias;

    [Write, Description (
        "This sets the NetBIOS name by which a Samba server is known."
        " By default it is the same as the first component of the "
        "host's DNS name. If a machine is a browse server or logon "
        "server this name (or the first component of the hosts DNS "
        "name) will be the name that these services are advertised "
        "under.")]
    string NetbiosName;

    [Write]
    boolean Printable;

    [Write, Description (
        "This controls what string will show up in the printer "
        "comment box in print manager and next to the IPC connection "
        "in net view. It can be any string that you wish to show to "
        "your users.\n"
        "It also sets what will appear in browse lists next to the "
        "machine name.\n"
        "A %v will be replaced with the Samba version number.\n"
        "A %h will be replaced with the hostname.")]
    string ServerString;

    [Write, Description (
        "This controls what workgroup your server will appear to be "
        "in when queried by clients. Note that this parameter also "
        "controls the Domain name used with the security = domain  "
        "setting.")]
    string Workgroup;
};


// ===================================================================
// Linux_SambaPrinterOptions
// ===================================================================
[Description("")]
class Linux_SambaPrinterOptions : CIM_SettingData {

    [Write]
    boolean Available;

    [Write]
    string Comment;

    [Key]
    string Name;

    [Write]
    string Path;

    [Write]
    boolean Printable = "yes";

    [Write]
    string SystemPrinterName;

    [Static]
    string getAllSystemDefinedPrinters();
};


// ===================================================================
// Linux_SambaLoggingOptions
// ===================================================================
class Linux_SambaLoggingOptions : CIM_SettingData {

    [Write]
    boolean DebugHiresTimestamp;

    [Write]
    boolean DebugPID;

    [Write]
    boolean DebugTimestamp;

    [Write]
    boolean DebugUID;

    [Write]
    string LogFile;

    [Write]
    string LogLevel;

    [Write]
    uint32 MaxLogSize;

    [Key]
    string Name;

    [Write, ValueMap ("\"0\",\"1\",\"2\",\"3\",\"4\""), Values (
        "\"LOG_ERR\",\"LOG_WARNING\",\"LOG_NOTICE\",\"LOG_INFO\","
        "\"LOG_DEBUG\"")]
    uint16 SysLog;

    [Write]
    boolean SysLogOnly;
};


// ===================================================================
// Linux_SambaPrinterSecurityOptions
// ===================================================================
[Description("")]
class Linux_SambaPrinterSecurityOptions : CIM_SettingData {

    [Key]
    string Name;
};


// ===================================================================
// Linux_SambaGlobalSecurityOptions
// ===================================================================
[Description("")]
class Linux_SambaGlobalSecurityOptions : CIM_SettingData {

    [Write]
    string AuthMethods;

    [Write]
    boolean EncryptPasswords;

    [Write]
    uint8 MinPasswordLength;

    [Key]
    string Name;

    [Write]
    boolean NullPasswords;

    [Write, ValueMap (
        "\"smbpasswd\", \"tdbsam\", \"ldapsam\", \"nisplussam\","
        " \"mysql\""), Values ("\"0\", \"1\", \"2\", \"3\", \"4\"")
        ]
    string PassdbBackend;

    [Write]
    string SMBPasswdFile;

    [Write, ValueMap (
        "\"User\", \"Share\", \"Server\", \"Domain\", \"ADS\"")
        , Values ("\"0\", \"1\", \"2\", \"3\", \"4\"")
        ]
    uint8 Security;
};


// ===================================================================
// Linux_SambaPrinterPrintingOptions
// ===================================================================
[Description("")]
class Linux_SambaPrinterPrintingOptions : CIM_SettingData {

    [Write]
    string CupsOptions;

    [Write]
    boolean DefaultDevMode;

    [Write]
    uint64 MaxPrintjobs;

    [Write]
    uint64 MaxReportedPrintjobs;

    [Key]
    string Name;

    [Write]
    string PrintCommand;

    [Write]
    boolean UseClientDriver;
};


// ===================================================================
// Linux_SambaGlobalFileNameHandlingOptions
// ===================================================================
[Description("")]
class Linux_SambaGlobalFileNameHandlingOptions : Linux_SambaShareFileNameHandlingOptions {

    [Key, Override ("Name")]
    string Name;
};


// ===================================================================
// Linux_SambaGlobalPrintingOptions
// ===================================================================
[Description("")]
class Linux_SambaGlobalPrintingOptions : Linux_SambaPrinterPrintingOptions {

    [Key, Override ("Name")]
    string Name;

    [Write]
    uint64 PrintcapCacheTime;

    [Write]
    string SystemPrinterName;
};


// ===================================================================
// Linux_SambaUser
// ===================================================================
[Description("")]
class Linux_SambaUser : CIM_ManagedElement {

    [Key, Description ("Samba user name ")]
    string SambaUserName;

    [Write, Read (false)]
    string SambaUserPassword;

    [Write, Override ("UserID"), Description ("User name as defined in system")]
    string SystemUserName;

    [Static]
    string getAllSystemGroups();

    [Static]
    string getAllSystemUsers();
};


// ===================================================================
// Linux_SambaCommonSecurityOptions
// ===================================================================
[Description("")]
class Linux_SambaCommonSecurityOptions : CIM_SettingData {

    [Write]
    boolean GuestOK;

    [Write]
    boolean GuestOnly;

    [Write, Description (
        "This parameter is a comma, space, or tab delimited set of "
        "hosts which are permitted to access a service")]
    string HostsAllow;

    [Write, Description (
        "The opposite of hosts allow - hosts listed here are NOT "
        "permitted access to services unless the specific services "
        "have their own lists to override this one. Where the lists "
        "conflict, the allow list takes precedence.\n\n")]
    string HostsDeny;

    [Key]
    string Name;

    [Write]
    boolean ReadOnly;
};


// ===================================================================
// Linux_SambaWinsOptions
// ===================================================================
class Linux_SambaWinsOptions : CIM_SettingData {

    [Write]
    string DNS_Proxy;

    [Key]
    string Name;

    [Write]
    string WINSHook;

    [Write]
    boolean WINSProxy;

    [Write]
    string WINSServer;

    [Write]
    boolean WINSSupport;
};


// ===================================================================
// Linux_SambaSharePrinterBrowseOptions
// ===================================================================
[Description("")]
class Linux_SambaSharePrinterBrowseOptions : CIM_SettingData {

    [Write, Description ("Can this share be advertised to the clients")]
    boolean Browsable;

    [Key]
    string Name;
};


// ===================================================================
// Linux_SambaGlobalBrowseOptions
// ===================================================================
[Description("")]
class Linux_SambaGlobalBrowseOptions : Linux_SambaSharePrinterBrowseOptions {

    [Write, ValueMap ("\"No\", \"Yes\", \"Auto\""), Values ("\"0\", \"1\", \"2\"")]
    uint16 DomainMaster;

    [Key, Override ("Name")]
    string Name;
};


// ===================================================================
// Linux_SambaScriptingOptions
// ===================================================================
[Description("")]
class Linux_SambaScriptingOptions : CIM_SettingData {

    [Key]
    string Name;

    [Write]
    string addGroupScript;

    [Write]
    string addPrinterCommand;

    [Write]
    String addShareCommand;

    [Write]
    string addUserScript;

    [Write]
    string addUsertoGroupScript;

    [Write]
    string deleteGrouprScript;

    [Write]
    string deleteUserScript;

    [Write]
    string deleteUserfromGroupScript;

    [Write]
    string setPrimaryGroupScript;
};


// ===================================================================
// Linux_SambaShareProtocolOptions
// ===================================================================
[Description("")]
class Linux_SambaShareProtocolOptions : CIM_SettingData {

    [Write, ValueMap ("\"Auto\",\"winnt\",\"win2k\""), Values (
        "\"0\",\"1\",\"2\"")
        , Description (
        "This parameter specifies what OS ACL semantics should be "
        "compatible with. Possible values are winnt for Windows NT 4,"
        " win2k for Windows 2000 and above and auto. If you specify "
        "auto, the value for this parameter will be based upon the "
        "version of the client. There should be no reason to change "
        "this parameter from the default.\n\n")]
    uint8 AclCompatibility;

    [Write, Description (
        "This boolean parameter controls whether smbd(8) will allow "
        "clients to attempt to store OS/2 style Extended attributes "
        "on a share. In order to enable this parameter the underlying"
        " filesystem exported by the share must support extended "
        "attributes (such as provided on XFS and EXT3 on Linux, with "
        "the correct kernel patches). On Linux the filesystem must "
        "have been mounted with the mount option user_xattr in order "
        "for extended attributes to work, also extended attributes "
        "must be compiled into the Linux kernel.")]
    boolean EASupport;

    [Write, Description (
        "This boolean parameter controls whether smbd(8) will attempt"
        " to map UNIX permissions into Windows NT access control "
        "lists. This parameter was formally a global parameter in "
        "releases prior to 2.2.2.\n\n")]
    boolean NTACLSupport;

    [Key]
    string Name;
};


// ===================================================================
// Linux_SambaGlobalProtocolOptions
// ===================================================================
[Description("")]
class Linux_SambaGlobalProtocolOptions : Linux_SambaShareProtocolOptions {

    [Key]
    string Name;
};


// ===================================================================
// Linux_SambaHost
// ===================================================================
[Description("")]
class Linux_SambaHost {

    [Key]
    string Name;
};


// ===================================================================
// Linux_SambaWinbindOptions
// ===================================================================
class Linux_SambaWinbindOptions : CIM_SettingData {

    [Key]
    string Name;
};


// ===================================================================
// Linux_SambaGroup
// ===================================================================
[Description("")]
class Linux_SambaGroup : CIM_ManagedElement {

    [Key]
    string SambaGroupName;

    [Write]
    string SystemGroupName;

    [Static]
    string getAllSystemGroups();
};


// ===================================================================
// Linux_SambaPrinterSecurityForPrinter
// ===================================================================
[Association, Description("")]
class Linux_SambaPrinterSecurityForPrinter : CIM_ElementSettingData {

    [Key, Min (1), Max (1)]
    Linux_SambaPrinterSecurityOptions REF SettingData;

    [Key, Min (1), Max (1)]
    Linux_SambaPrinterOptions REF ManagedElement;
};


// ===================================================================
// Linux_SambaGlobalSecurityForGlobal
// ===================================================================
[Association, Description("")]
class Linux_SambaGlobalSecurityForGlobal : CIM_ElementSettingData {

    [Min (1), Max (1)]
    Linux_SambaGlobalSecurityOptions REF SettingData;

    [Min (1), Max (1)]
    Linux_SambaGlobalOptions REF ManagedElement;
};


// ===================================================================
// Linux_SambaLoggingForGlobal
// ===================================================================
[Association]
class Linux_SambaLoggingForGlobal : CIM_ElementSettingData {

    [Min (1), Max (1)]
    Linux_SambaLoggingOptions REF SettingData;

    [Min (1), Max (1)]
    Linux_SambaGlobalOptions REF ManagedElement;
};


// ===================================================================
// Linux_SambaPrinterPrintingForPrinter
// ===================================================================
[Association, Description("")]
class Linux_SambaPrinterPrintingForPrinter : CIM_ElementSettingData {

    [Min (1), Max (1)]
    Linux_SambaPrinterPrintingOptions REF SettingData;

    [Min (1), Max (1)]
    Linux_SambaPrinterOptions REF ManagedElement;
};


// ===================================================================
// Linux_SambaShareSecurityForShare
// ===================================================================
[Association, Description("")]
class Linux_SambaShareSecurityForShare : CIM_ElementSettingData {

    [Min (1), Max (1)]
    Linux_SambaShareSecurityOptions REF SettingData;

    [Min (1), Max (1)]
    Linux_SambaShareOptions REF ManagedElement;
};


// ===================================================================
// Linux_SambaShareFileNameHandlingForShare
// ===================================================================
[Association, Description("")]
class Linux_SambaShareFileNameHandlingForShare : CIM_ElementSettingData {

    [Min (1), Max (1)]
    Linux_SambaShareFileNameHandlingOptions REF SettingData;

    [Min (1), Max (1)]
    Linux_SambaShareOptions REF ManagedElement;
};


// ===================================================================
// Linux_SambaServiceConfigurationForService
// ===================================================================
[Association, Description (
    "Association between a Samba Service and its configuration")]
class Linux_SambaServiceConfigurationForService : CIM_ElementConfiguration {

    [Key, Min (1), Max (1)]
    Linux_SambaServiceConfiguration REF Configuration;

    [Key, Min (1), Max (1)]
    Linux_SambaService REF Element;
};


// ===================================================================
// Linux_SambaGlobalFileNameHandlingForGlobal
// ===================================================================
[Association, Description("")]
class Linux_SambaGlobalFileNameHandlingForGlobal : CIM_ElementSettingData {

    [Min (1), Max (1)]
    Linux_SambaGlobalOptions REF ManagedElement;

    [Min (1), Max (1)]
    Linux_SambaGlobalFileNameHandlingOptions REF SettingData;
};


// ===================================================================
// Linux_SambaGlobalPrintingForGlobal
// ===================================================================
[Association, Description("")]
class Linux_SambaGlobalPrintingForGlobal : CIM_ElementSettingData {

    [Min (1), Max (1)]
    Linux_SambaGlobalPrintingOptions REF SettingData;

    [Min (1), Max (1)]
    Linux_SambaGlobalOptions REF ManagedElement;
};


// ===================================================================
// Linux_SambaShareSecurityForGlobal
// ===================================================================
[Association, Description("")]
class Linux_SambaShareSecurityForGlobal : CIM_ElementSettingData {

    [Min (1), Max (1)]
    Linux_SambaShareSecurityOptions REF SettingData;

    [Min (1), Max (1)]
    Linux_SambaGlobalOptions REF ManagedElement;
};


// ===================================================================
// Linux_SambaPrinterSecurityForGlobal
// ===================================================================
[Association, Description("")]
class Linux_SambaPrinterSecurityForGlobal : CIM_ElementSettingData {

    [Min (1), Max (1)]
    Linux_SambaPrinterSecurityOptions REF SettingData;

    [Min (1), Max (1)]
    Linux_SambaGlobalOptions REF ManagedElement;
};


// ===================================================================
// Linux_SambaCommonSecurityForGlobal
// ===================================================================
[Association, Description("")]
class Linux_SambaCommonSecurityForGlobal : CIM_ElementSettingData {

    [Min (1), Max (1)]
    Linux_SambaCommonSecurityOptions REF SettingData;

    [Min (1), Max (1)]
    Linux_SambaGlobalOptions REF ManagedElement;
};


// ===================================================================
// Linux_SambaCommonSecurityForPrinter
// ===================================================================
[Association, Description("")]
class Linux_SambaCommonSecurityForPrinter : CIM_ElementSettingData {

    [Min (1), Max (1)]
    Linux_SambaCommonSecurityOptions REF SettingData;

    [Min (1), Max (1)]
    Linux_SambaPrinterOptions REF ManagedElement;
};


// ===================================================================
// Linux_SambaCommonSecurityForShare
// ===================================================================
[Association, Description("")]
class Linux_SambaCommonSecurityForShare : CIM_ElementSettingData {

    [Min (1), Max (1)]
    Linux_SambaCommonSecurityOptions REF SettingData;

    [Min (1), Max (1)]
    Linux_SambaShareOptions REF ManagedElement;
};


// ===================================================================
// Linux_SambaGlobalForService
// ===================================================================
[Association, Description("")]
class Linux_SambaGlobalForService : CIM_ElementSettingData {

    [Min (1), Max (1)]
    Linux_SambaGlobalOptions REF SettingData;

    [Min (1), Max (1)]
    Linux_SambaService REF ManagedElement;
};


// ===================================================================
// Linux_SambaShareForService
// ===================================================================
[Association, Description("")]
class Linux_SambaShareForService : CIM_ElementSettingData {

    Linux_SambaShareOptions REF SettingData;

    [Min (1), Max (1)]
    Linux_SambaService REF ManagedElement;
};


// ===================================================================
// Linux_SambaPrinterForService
// ===================================================================
[Association, Description("")]
class Linux_SambaPrinterForService : CIM_ElementSettingData {

    Linux_SambaPrinterOptions REF SettingData;

    [Min (1), Max (1)]
    Linux_SambaService REF ManagedElement;
};


// ===================================================================
// Linux_SambaGuestAccountForGlobal
// ===================================================================
[Association, Aggregation, Description("")]
class Linux_SambaGuestAccountForGlobal : CIM_Component {

    [Aggregate, Min (1), Max (1)]
    Linux_SambaUser REF PartComponent;

    [Min (1), Max (1)]
    Linux_SambaGlobalOptions REF GroupComponent;
};


// ===================================================================
// Linux_SambaAdminUsersForGlobal
// ===================================================================
[Association, Aggregation, Description("")]
class Linux_SambaAdminUsersForGlobal : CIM_Component {

    [Aggregate]
    Linux_SambaUser REF PartComponent;

    [Min (1), Max (1)]
    Linux_SambaGlobalOptions REF GroupComponent;
};


// ===================================================================
// Linux_SambaReadListForGlobal
// ===================================================================
[Association, Aggregation, Description("")]
class Linux_SambaReadListForGlobal : CIM_Component {

    [Aggregate]
    Linux_SambaUser REF PartComponent;

    [Min (1), Max (1)]
    Linux_SambaGlobalOptions REF GroupComponent;
};


// ===================================================================
// Linux_SambaWriteListForGlobal
// ===================================================================
[Association, Aggregation, Description("")]
class Linux_SambaWriteListForGlobal : CIM_Component {

    [Aggregate]
    Linux_SambaUser REF PartComponent;

    [Min (1), Max (1)]
    Linux_SambaGlobalOptions REF GroupComponent;
};


// ===================================================================
// Linux_SambaForceUserForGlobal
// ===================================================================
[Association, Aggregation, Description("")]
class Linux_SambaForceUserForGlobal : CIM_Component {

    [Aggregate, Min (1), Max (1)]
    Linux_SambaUser REF PartComponent;

    [Min (1), Max (1)]
    Linux_SambaGlobalOptions REF GroupComponent;
};


// ===================================================================
// Linux_SambaInvalidUsersForGlobal
// ===================================================================
[Association, Aggregation, Description("")]
class Linux_SambaInvalidUsersForGlobal : CIM_Component {

    [Aggregate]
    Linux_SambaUser REF PartComponent;

    [Min (1), Max (1)]
    Linux_SambaGlobalOptions REF GroupComponent;
};


// ===================================================================
// Linux_SambaValidUsersForGlobal
// ===================================================================
[Association, Aggregation, Description("")]
class Linux_SambaValidUsersForGlobal : CIM_Component {

    [Aggregate]
    Linux_SambaUser REF PartComponent;

    [Min (1), Max (1)]
    Linux_SambaGlobalOptions REF GroupComponent;
};


// ===================================================================
// Linux_SambaPrinterAdminForGlobal
// ===================================================================
[Association, Aggregation, Description("")]
class Linux_SambaPrinterAdminForGlobal : CIM_Component {

    [Aggregate]
    Linux_SambaUser REF PartComponent;

    [Min (1), Max (1)]
    Linux_SambaGlobalOptions REF GroupComponent;
};


// ===================================================================
// Linux_SambaWinsForGlobal
// ===================================================================
[Association]
class Linux_SambaWinsForGlobal : CIM_ElementSettingData {

    [Min (1), Max (1)]
    Linux_SambaWinsOptions REF SettingData;

    [Min (1), Max (1)]
    Linux_SambaGlobalOptions REF ManagedElement;
};


// ===================================================================
// Linux_SambaPrinterAdminForPrinter
// ===================================================================
[Association, Aggregation, Description("")]
class Linux_SambaPrinterAdminForPrinter : CIM_Component {

    [Aggregate]
    Linux_SambaUser REF PartComponent;

    Linux_SambaPrinterOptions REF GroupComponent;
};


// ===================================================================
// Linux_SambaReadListForPrinter
// ===================================================================
[Association, Aggregation, Description("")]
class Linux_SambaReadListForPrinter : CIM_Component {

    [Aggregate]
    Linux_SambaUser REF PartComponent;

    Linux_SambaPrinterOptions REF GroupComponent;
};


// ===================================================================
// Linux_SambaWriteListForPrinter
// ===================================================================
[Association, Aggregation, Description("")]
class Linux_SambaWriteListForPrinter : CIM_Component {

    [Aggregate]
    Linux_SambaUser REF PartComponent;

    Linux_SambaPrinterOptions REF GroupComponent;
};


// ===================================================================
// Linux_SambaForceUserForPrinter
// ===================================================================
[Association, Aggregation, Description("")]
class Linux_SambaForceUserForPrinter : CIM_Component {

    [Aggregate]
    Linux_SambaUser REF PartComponent;

    Linux_SambaPrinterOptions REF GroupComponent;
};


// ===================================================================
// Linux_SambaInvalidUsersForPrinter
// ===================================================================
[Association, Aggregation, Description("")]
class Linux_SambaInvalidUsersForPrinter : CIM_Component {

    [Aggregate]
    Linux_SambaUser REF PartComponent;

    Linux_SambaPrinterOptions REF GroupComponent;
};


// ===================================================================
// Linux_SambaValidUsersForPrinter
// ===================================================================
[Association, Aggregation, Description("")]
class Linux_SambaValidUsersForPrinter : CIM_Component {

    [Aggregate]
    Linux_SambaUser REF PartComponent;

    Linux_SambaPrinterOptions REF GroupComponent;
};


// ===================================================================
// Linux_SambaAdminUsersForShare
// ===================================================================
[Association, Aggregation, Description("")]
class Linux_SambaAdminUsersForShare : CIM_Component {

    [Aggregate]
    Linux_SambaUser REF PartComponent;

    Linux_SambaShareOptions REF GroupComponent;
};


// ===================================================================
// Linux_SambaReadListForShare
// ===================================================================
[Association, Aggregation, Description("")]
class Linux_SambaReadListForShare : CIM_Component {

    [Aggregate]
    Linux_SambaUser REF PartComponent;

    Linux_SambaShareOptions REF GroupComponent;
};


// ===================================================================
// Linux_SambaWriteListForShare
// ===================================================================
[Association, Aggregation, Description("")]
class Linux_SambaWriteListForShare : CIM_Component {

    [Aggregate]
    Linux_SambaUser REF PartComponent;

    Linux_SambaShareOptions REF GroupComponent;
};


// ===================================================================
// Linux_SambaForceUserForShare
// ===================================================================
[Association, Aggregation, Description("")]
class Linux_SambaForceUserForShare : CIM_Component {

    [Aggregate]
    Linux_SambaUser REF PartComponent;

    Linux_SambaShareOptions REF GroupComponent;
};


// ===================================================================
// Linux_SambaInvalidUsersForShare
// ===================================================================
[Association, Aggregation, Description("")]
class Linux_SambaInvalidUsersForShare : CIM_Component {

    [Aggregate]
    Linux_SambaUser REF PartComponent;

    Linux_SambaShareOptions REF GroupComponent;
};


// ===================================================================
// Linux_SambaValidUsersForShare
// ===================================================================
[Association, Aggregation, Description("")]
class Linux_SambaValidUsersForShare : CIM_Component {

    [Aggregate]
    Linux_SambaUser REF PartComponent;

    Linux_SambaShareOptions REF GroupComponent;
};


// ===================================================================
// Linux_SambaSharePrinterBrowseForShare
// ===================================================================
[Association, Description("")]
class Linux_SambaSharePrinterBrowseForShare : CIM_ElementSettingData {

    [Min (1), Max (1)]
    Linux_SambaSharePrinterBrowseOptions REF SettingData;

    [Min (1), Max (1)]
    Linux_SambaShareOptions REF ManagedElement;
};


// ===================================================================
// Linux_SambaGlobalBrowseForGlobal
// ===================================================================
[Association, Description("")]
class Linux_SambaGlobalBrowseForGlobal : CIM_ElementSettingData {

    [Min (1), Max (1)]
    Linux_SambaGlobalBrowseOptions REF SettingData;

    [Min (1), Max (1)]
    Linux_SambaGlobalOptions REF ManagedElement;
};


// ===================================================================
// Linux_SambaUsersForService
// ===================================================================
[Association, Aggregation, Description("")]
class Linux_SambaUsersForService : CIM_Component {

    [Aggregate]
    Linux_SambaUser REF PartComponent;

    [Min (1), Max (1)]
    Linux_SambaService REF GroupComponent;
};


// ===================================================================
// Linux_SambaScriptingForGlobal
// ===================================================================
[Association, Description("")]
class Linux_SambaScriptingForGlobal : CIM_ElementSettingData {

    [Min (1), Max (1)]
    Linux_SambaGlobalOptions REF ManagedElement;

    [Min (1), Max (1)]
    Linux_SambaScriptingOptions REF SettingData;
};


// ===================================================================
// Linux_SambaShareProtocolForShare
// ===================================================================
[Association, Description("")]
class Linux_SambaShareProtocolForShare : CIM_ElementSettingData {

    [Min (1), Max (1)]
    Linux_SambaShareOptions REF ManagedElement;

    [Min (1), Max (1)]
    Linux_SambaShareProtocolOptions REF SettingData;
};


// ===================================================================
// Linux_SambaGlobalProtocolForGlobal
// ===================================================================
[Association, Description("")]
class Linux_SambaGlobalProtocolForGlobal : CIM_ElementSettingData {

    [Min (1), Max (1)]
    Linux_SambaGlobalProtocolOptions REF SettingData;

    [Min (1), Max (1)]
    Linux_SambaGlobalOptions REF ManagedElement;
};


// ===================================================================
// Linux_SambaSharePrinterBrowseForPrinter
// ===================================================================
[Association, Description("")]
class Linux_SambaSharePrinterBrowseForPrinter : CIM_ElementSettingData {

    [Min (1), Max (1)]
    Linux_SambaPrinterOptions REF ManagedElement;

    [Min (1), Max (1)]
    Linux_SambaSharePrinterBrowseOptions REF SettingData;
};


// ===================================================================
// Linux_SambaGroupForUser
// ===================================================================
[Association, Aggregation, Description("")]
class Linux_SambaGroupForUser : CIM_Component {

    [Aggregate]
    Linux_SambaGroup REF GroupComponent;

    [Min (1), Max (1)]
    Linux_SambaUser REF PartComponent;
};


// ===================================================================
// Linux_SambaWinbindForGlobal
// ===================================================================
[Association]
class Linux_SambaWinbindForGlobal : CIM_ElementSettingData {

    [Min (1), Max (1)]
    Linux_SambaWinbindOptions REF SettingData;

    [Min (1), Max (1)]
    Linux_SambaGlobalOptions REF ManagedElement;
};


// ===================================================================
// Linux_SambaForceGroupForGlobal
// ===================================================================
[Association, Description("")]
class Linux_SambaForceGroupForGlobal : CIM_Component {

    Linux_SambaGlobalOptions REF GroupComponent;

    [Min (1), Max (1)]
    Linux_SambaGroup REF PartComponent;
};


// ===================================================================
// Linux_SambaForceGroupForShare
// ===================================================================
[Association, Description("")]
class Linux_SambaForceGroupForShare : CIM_Component {

    Linux_SambaShareOptions REF GroupComponent;

    [Min (1), Max (1)]
    Linux_SambaGroup REF PartComponent;
};


// ===================================================================
// Linux_SambaForceGroupForPrinter
// ===================================================================
[Association, Description("")]
class Linux_SambaForceGroupForPrinter : CIM_Component {

    Linux_SambaPrinterOptions REF GroupComponent;

    [Min (1), Max (1)]
    Linux_SambaGroup REF PartComponent;
};

// ===================================================================
// end of file
// ===================================================================

